module.exports = [
    'culiao',
    'perkin',
    'enfermo',
    'sapo ctm',
    'gil',
    'aweonao',
    'comemoco',
    'soperutano',
    'conchetumare',
    'jolaperra',
    'pajaron',
    'tai vio si',
    'hijo de la tragasable',
    'perhuetano',
    'mono kl',
    'bastardo',
    'pollo',
    'gorrino',
    'weon tonto',
    'inútil',
    'desperdicio',
    'mojón mal cagao',
    'chupa quesillo',
    'lamprea',
    'lumpen ql'
]
